### ISSUE TITLE
Insert text: DIVE DEEPER INTO THE BLOCKCHAIN

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparklearn-web-app#34]
Image for reference: 
![image](https://user-images.githubusercontent.com/61826995/119100961-0f7b8980-ba4b-11eb-85d6-3ae84227c68f.png)

**Comment by crs26** [comment]
![image](https://user-images.githubusercontent.com/55611653/119440276-933cbb00-bd56-11eb-8296-dc87cad9db28.png)

**Comment by Pseudoman21** [comment]
Test

**Comment by swengr-janan** [comment]
Fixed
