### ISSUE TITLE
Insert text: LET'S HEAR IT FROM THEM

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparklearn-web-app#36]
Image for reference: 
![image](https://user-images.githubusercontent.com/61826995/119101243-59646f80-ba4b-11eb-981a-dc4a35f9b57b.png)

**Comment by crs26** [comment]
Inserted
![image](https://user-images.githubusercontent.com/55611653/119440125-5244a680-bd56-11eb-8414-580bfb0efc02.png)

**Comment by swengr-janan** [comment]
Fixed
