### ISSUE TITLE
Change the course titles

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparklearn-web-app#58]
Blockchain Technology
Decentralized Finance
Financial Literacy

When the user clicks the course image, he/she can view the course through guest access in Moodle. 

Use the video cover for the image in the course title

![image](https://user-images.githubusercontent.com/61826995/125228159-e66acd00-e306-11eb-9943-58d9bd3253de.png)

**Comment by crs26** [comment]
Yung course name po naka depend yan sa kung ano ilalagay na course shortname sa moodle settings. Tapos yung thumbnail po okay na daw yung PNG/JPEG

**Comment by swengr-janan** [comment]
Ah okay @crs26 , close ko na to?

**Comment by crs26** [comment]
Opo sir

**Comment by swengr-janan** [comment]
Oki. Thanks @crs26 !
